[정수론] 3월 5일
Altu-Bitu-6/Altu-Bitu-LeeEunseo pull request #1
Opened 2024-03-05 14:57 UTC by monimoni12

### 인적사항
학번: 2076320
이름: 이은서
</br>

### 과제제출
기존제출: 1735, 2840, 6588
</br>

2024-03-08 08:06 UTC, chae-jpg requested changes
**[정수론 이론 코드리뷰 완료]**

1735(P3), 6588(P1)
은서님 안녕하세요! 코드 리뷰 완료되었습니다👍
현재 6588번에서 P1 판정이 나오고 있습니다 😢 
리뷰 확인하시고 수정 후 다시 리뷰어 호출 부탁드립니다!
궁금하신 점이 있다면 언제나 리뷰어를 호출해주세요😊

2024-03-08 08:06 UTC, chae-jpg commented on 03_정수론/1735.cpp
> +int gcd(int d1, int d2){
유클리드 호제법을 잘 구현해주셨어요!

2024-03-08 08:06 UTC, chae-jpg commented on 03_정수론/1735.cpp
> +    else
위에서 리턴을 해주고 있기 때문에 꼭 else를 붙이지 않아도 됩니다!

2024-03-08 08:06 UTC, chae-jpg commented on 03_정수론/1735.cpp
> +        return gcd(d2,r);
P3
알튜비튜에서는 협업, 수정 시의 실수를 막기 위해 한 줄의 코드여도 중괄호 사용을 권장하고 있어요~
중괄호 추가해주시면 더 좋을 것 같습니다!

2024-03-08 08:06 UTC, chae-jpg commented on 03_정수론/1735.cpp
> +    cout << a*(lcm/b)+c*(lcm/d) << " " << lcm << "\n";
기약분수가 되기 위한 조건을 이용해서 새로운 분자와 분모를 잘 찾아주셨네요!

2024-03-08 08:06 UTC, chae-jpg commented on 03_정수론/6588.cpp
> +vector<int> sieveOfEratosthenes(int n) {
에라토스테네스의 체를 이용해서 소수를 잘 판정해주셨네요!

2024-03-08 08:06 UTC, chae-jpg commented on 03_정수론/6588.cpp
> +    }
위에서 소수를 판정할 때 같이 푸시하면 연산과 시간을 줄일 수 있을 것 같아요!

2024-03-08 08:06 UTC, chae-jpg commented on 03_정수론/6588.cpp
> +            }
P1
지금 이 부분에서 시간이 너무 많이 소요됩니다 😢 
소수 하나의 가능한 모든 순서쌍을 확인하기 때문에 시간복잡도가 n^2가 되고, 이는 굉장히 큰 시간이 걸리죠! 😞 
이전에 구한 소수 여부 배열을 함께 사용하면 더 효율적으로 구할 수 있는 방법이 있지 않을까요?

2024-03-08 08:06 UTC, chae-jpg commented on 03_정수론/6588.cpp
> +    cin >> n;
P1
문제에서 n은 0일 때까지 계속해서 주어지기 때문에 지금처럼 한 번 받는 것이 아니라 0일 때까지 계속 받도록 설정해야 합니다!

2024-03-08 10:21 UTC, kimhj010502 reviewed
**[정수론 구현 문제 코드 리뷰 완료]**

2840(P2)

은서님 안녕하세요!
과제하시느라 수고 많으셨습니다!! 어려운 문제인데도 잘 풀어주셨네요! 🥰
코드에 대한 간단한 주석이 있으면 더 좋을 것 같아요. 😎
몇 가지 사소한 코멘트 드렸습니다.
궁금한 점이 있으면 리뷰어를 호출해주세요!

2024-03-08 10:21 UTC, kimhj010502 commented on 03_정수론/2840.cpp
> +int main(){
P2. 모든 연산을 main 함수에서 해주었네요~ 알튜비튜에서는 함수로 구현할 수 있는 부분은 최대한 함수를 따로 정의해서 사용하는 것을 권장하고 있어요!

2024-03-08 10:21 UTC, kimhj010502 commented on 03_정수론/2840.cpp
> +    cin >> N >> K >> S;
P2. 변수 이름은 스네이크 표기법으로 작성해주세요!

2024-03-08 10:21 UTC, kimhj010502 commented on 03_정수론/2840.cpp
> +    fill(wheel, wheel + N, '?');
char 배열을 `vector<char> wheel(N, '?');`로 작성해주면 따로 `fill`하지 않아도 됩니다!

2024-03-08 10:21 UTC, kimhj010502 commented on 03_정수론/2840.cpp
> +        char c;
계속 사용할 변수는 반복문 밖에서 한 번만 정의해주는 것이 메모리 관리 측면에서 좋습니다!

2024-03-08 10:21 UTC, kimhj010502 commented on 03_정수론/2840.cpp
> +            wheel[j % N] = c;
조건문을 사용할 때 중괄호가 없으면 나중에 수정할 일이 있을 때 불편할 일이 생길 수 있어요 한줄짜리 조건문도 중괄호를 사용해주세요!

2024-03-10 13:42 UTC, chae-jpg requested changes
안녕하세요 은서님! 코드에서 수정 필요한 부분이 있어 다시 코멘트 드립니다 😢
리뷰 확인 후 수정하신 뒤, 다시 리뷰어를 호출해주세요!

2024-03-27 00:59 UTC, monimoni12 commented on 03_정수론/1735.cpp
> +    else
조금 더 상세히 설명해주실 수 있을까요,,!

2024-04-11 13:28 UTC, chae-jpg approved these changes
안녕하세요 은서님! 제출 확인되었습니다!
머지하셔도 좋습니다~ 수고하셨습니다!

2024-04-11 13:57 UTC, merged